/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BuyGpsRouteImport } from './routes/buy-gps'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as PtlRouteImport } from './routes/ptl'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as TruckOwnerDashboardRouteImport } from './routes/truck-owner/dashboard'
import { Route as TruckOwnerLoginRouteImport } from './routes/truck-owner/login'
import { Route as TsCityRouteImport } from './routes/ts/$city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyGpsRoute = BuyGpsRouteImport.update({
  id: '/buy-gps',
  path: '/buy-gps',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const PtlRoute = PtlRouteImport.update({
  id: '/ptl',
  path: '/ptl',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TruckOwnerDashboardRoute = TruckOwnerDashboardRouteImport.update({
  id: '/truck-owner/dashboard',
  path: '/truck-owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TruckOwnerLoginRoute = TruckOwnerLoginRouteImport.update({
  id: '/truck-owner/login',
  path: '/truck-owner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TsCityRoute = TsCityRouteImport.update({
  id: '/ts/$city',
  path: '/ts/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/buy-gps': typeof BuyGpsRoute
  '/careers': typeof CareersRoute
  '/ptl': typeof PtlRoute
  '/admin/login': typeof AdminLoginRoute
  '/truck-owner/dashboard': typeof TruckOwnerDashboardRoute
  '/truck-owner/login': typeof TruckOwnerLoginRoute
  '/ts/$city': typeof TsCityRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/buy-gps': typeof BuyGpsRoute
  '/careers': typeof CareersRoute
  '/ptl': typeof PtlRoute
  '/admin/login': typeof AdminLoginRoute
  '/truck-owner/dashboard': typeof TruckOwnerDashboardRoute
  '/truck-owner/login': typeof TruckOwnerLoginRoute
  '/ts/$city': typeof TsCityRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/buy-gps': typeof BuyGpsRoute
  '/careers': typeof CareersRoute
  '/ptl': typeof PtlRoute
  '/admin/login': typeof AdminLoginRoute
  '/truck-owner/dashboard': typeof TruckOwnerDashboardRoute
  '/truck-owner/login': typeof TruckOwnerLoginRoute
  '/ts/$city': typeof TsCityRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/buy-gps'
    | '/careers'
    | '/ptl'
    | '/admin/login'
    | '/truck-owner/dashboard'
    | '/truck-owner/login'
    | '/ts/$city'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/buy-gps'
    | '/careers'
    | '/ptl'
    | '/admin/login'
    | '/truck-owner/dashboard'
    | '/truck-owner/login'
    | '/ts/$city'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/buy-gps'
    | '/careers'
    | '/ptl'
    | '/admin/login'
    | '/truck-owner/dashboard'
    | '/truck-owner/login'
    | '/ts/$city'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  BuyGpsRoute: typeof BuyGpsRoute
  CareersRoute: typeof CareersRoute
  PtlRoute: typeof PtlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  TruckOwnerDashboardRoute: typeof TruckOwnerDashboardRoute
  TruckOwnerLoginRoute: typeof TruckOwnerLoginRoute
  TsCityRoute: typeof TsCityRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-gps': {
      id: '/buy-gps'
      path: '/buy-gps'
      fullPath: '/buy-gps'
      preLoaderRoute: typeof BuyGpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ptl': {
      id: '/ptl'
      path: '/ptl'
      fullPath: '/ptl'
      preLoaderRoute: typeof PtlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truck-owner/dashboard': {
      id: '/truck-owner/dashboard'
      path: '/truck-owner/dashboard'
      fullPath: '/truck-owner/dashboard'
      preLoaderRoute: typeof TruckOwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truck-owner/login': {
      id: '/truck-owner/login'
      path: '/truck-owner/login'
      fullPath: '/truck-owner/login'
      preLoaderRoute: typeof TruckOwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ts/$city': {
      id: '/ts/$city'
      path: '/ts/$city'
      fullPath: '/ts/$city'
      preLoaderRoute: typeof TsCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  BuyGpsRoute: BuyGpsRoute,
  CareersRoute: CareersRoute,
  PtlRoute: PtlRoute,
  AdminLoginRoute: AdminLoginRoute,
  TruckOwnerDashboardRoute: TruckOwnerDashboardRoute,
  TruckOwnerLoginRoute: TruckOwnerLoginRoute,
  TsCityRoute: TsCityRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
